#Datos de la cadena Conexion
nombre_maquinavirtual:
usuario_servidor:
password_servidor:
nombre_ip_servidor:
nombre_cluster:
nombre_datacenter:

#Path Directorio sysconfig
path_iptables: /etc/sysconfig/
#Grupo propietario fichero IpTables
grupo_iptables: root
#Grupo propietario fichero IpTables
usuario_iptables: root
#Permisos fichero IpTables
permisos_iptables: 0600
