- name: Ejecutar Fichero PostInstalacion root en Nodo-2
  become: yes
  become_user: "{{ usuario_root }}"
  shell: "{{ path_oracle_grid }}/root.sh"
  when: inventory_hostname == "{{ ip_nombre_node2 }}"

- name: Preparar Template para el Grid Response
  template:
    src: "{{ nombre_original_config_grid_template }}"
    dest: "{{ path_oracle_stage }}/{{ nombre_config_grid_template }}"
    owner: "{{ usuario_grid }}"
    group: "{{ grupo_oracle }}"
    mode: "{{ permisos_oracle }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Ejecutar Script configToolAllCommands
  become: yes
  become_user: "{{ usuario_grid }}"
  shell: "{{ path_oracle_grid }}/cfgtoollogs/configToolAllCommands RESPONSE_FILE={{ path_oracle_stage }}/{{ nombre_config_grid_template }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"
  ignore_errors: true

- name: Terminada Configuracion del Fichero configToolAllCommands
  debug:
    msg: "Configuracion del fichero configToolAllCommands en Nodo 1 Terminada, comando nativo sin retorno"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Crear +Fra Diskgroup
  become: yes
  become_user: "{{ usuario_grid }}"
  shell: "{{ path_oracle_grid }}/bin/asmca -silent -sysAsmPassword {{ password_asm_sys }} -asmsnmpPassword {{ asm_dbsnmp }} -createDiskGroup -diskString {{ path_discos_asm }} -diskGroupName {{ nombre_diskgroup_fra }} -diskList {{ discos_diskgroup_asm_fra }} -redundancy {{ redundancia_asm }}"
  # shell: "{{gi_home}}/bin/asmca -silent -sysAsmPassword {{ asm_passwd }} -asmsnmpPassword {{ asm_dbsnmp }} -createDiskGroup -diskString {{ asm_diskprefix }} -diskGroupName {{ asm_sec_dg }} -diskList {{ asm_disklist_s }} -redundancy {{ asm_redundancy}}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Resultado de la Instalacion de Grid
  become: yes
  become_user: "{{ usuario_grid }}"
  command: "/grid/bin/crsctl status resource -t"
  register: crsctl_result
  when: inventory_hostname == "{{ ip_nombre_node1 }}"
