- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Instalar NTP
  yum:
    name: "ntp"
    state: present

- name: Eliminar configuracion por defecto de hora y fecha
  lineinfile:
    path: "{{ path_ntp }}"
    regexp: "^server.*$"
    state: absent

- name: Agregar Servidores NTP
  lineinfile:
    path: "{{ path_ntp }}"
    insertbefore: ".*broadcast 192.168.1.255 autokey"
    line: "server {{ item }} iburst"
  loop: "{{ ntp_servers }}"

- name: Iniciar-Ntp
  service:
    name: ntpd
    enabled: true
    state: restarted
