nombre_directorio_certificacion: "/Certifi-servicios"
nombre_fichero_certificacion: "Certifi-servicios.txt"
path_certificacion: "{{nombre_directorio_certificacion}}/{{nombre_fichero_certificacion}}"

path_iptables: /etc/sysconfig/iptables
path_fstab: /etc/fstab

lista_ficheros_copiar_etc:
  - /etc/hosts
