- name: "Ejecutar Instalacion Oracle DataBase Cluster 12c"
  hosts: all
  become: true
  roles:
    - configSelinux
    - configNtp
    - configHosts
    - usersOracle
    - createDirectories
    - setVariables
    # - installOracle12cCluster
