- name: Instalar NTP
  yum:
    name: 'ntp'
    state: present

- name: Eliminar configuracion por defecto de hora y fecha
  lineinfile:
    path: "{{ path_ntp }}"
    regexp: '^server.*$'
    state: absent

- name: Agregar Servidores NTP
  lineinfile:
    path: "{{ path_ntp }}"
    line: 'server {{ item }} iburst'
  loop: "{{ ntp_servers }}"

- name: Iniciar-Ntp
  service:
    name: ntpd
    enabled: true
    state: restarted
