- name: Crear Directorio Summary
  file:
    path: "{{ directorio_summary }}"
    state: directory
    force: yes

- name: Crear Archivo Summary
  file:
    path: "{{ nombre_sumary }}_{{ path_summary }}{{ extension_summary }}"
    state: touch

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_summary }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  Resumen de Ejecucion  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

  # debug:
  #   msg: "{{ lookup('pipe','date + %Y-%m-%d-%H-%M-%S') }}"
