- name: Generar llave para usuarios Oracle
  user:
    name: "{{ usuario_oracle }}"
    generate_ssh_key: yes
    state: present

- name: Descargar llaves publicas Nodo 1
  fetch:
    src: "/home/{{ usuario_oracle }}/.ssh/id_rsa.pub"
    dest: "oracle_id_rsa.{{ ip_nombre_node1 }}"
    flat: yes
  with_items: "{{groups['all']}}"

- name: Descargar llaves publicas Nodo 2
  fetch:
    src: "/home/{{ usuario_oracle }}/.ssh/id_rsa.pub"
    dest: "oracle_id_rsa.{{ ip_nombre_node2 }}"
    flat: yes
  with_items: "{{groups['all']}}"

- name: Copiar llaves Publicas a todos los nodos
  become: yes
  become_user: "{{ usuario_become }}"
  authorized_key:
    user: "{{ usuario_oracle }}"
    key: "{{ lookup('file', 'oracle_id_rsa.{{ item }}') }}"
    state: present
  loop: "{{groups['all']}}"

- name: Make sure the known hosts file exists
  become: yes
  become_user: "{{ usuario_become }}"
  file:
    path: ~/.ssh/known_hosts
    state: touch

- name: Agregar hosts al fichero known_hosts
  become: yes
  become_user: "{{ usuario_become }}"
  shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
  loop: "{{groups['all']}}"
