- name: Crear Directorio Certifi-servicios
  file:
    path: /{{nombre_directorio_certificacion}}
    state: directory
    force: yes
- name: Copiar Ficheros a Certifi-servicios
  copy:
    src: "{{ item }}"
    dest: /{{nombre_directorio_certificacion}}
    force: yes
  loop: "{{ lista_ficheros_copiar_etc }}"
  ignore_errors: yes
- name: Copiar Ficheros sshd_config a Certifi-servicios
  command: cat /etc/ssh/sshd_config
  register: sshdconfig_out
- name: ---- Data ----
  debug:
    msg: "Actualizaciones: {{ sshdconfig_out.stdout  }}"
- name: Copiar Ficheros sshd_config a Certifi-servicios
  copy:
    content: {{ sshdconfig_out.stdout }}
    dest: /{{nombre_directorio_certificacion}}/sshd_config

# - name: Copiar Ficheros sshd_config a Certifi-servicios
#   shell: cat /etc/ssh/sshd_config >> /Certifi-servicios/sshd_config
# - name: Crear Fichero Certifi-servicios
#   copy:
#     content: ""
#     dest: /Certifi-servicios/Certifi-servicios.txt
#     force: yes
# - name: Imprimir Linea Inicial
#     lineinfile:
#       path: /etc/ntp.conf
#       line: 'server {{ item }} iburst'


#
#
# - name: Imprimir Linea Inicial
#   shell: |
#     echo '############################################ SERVICIOS ACTIVOS #################################################################################' >> /Certifi-servicios/Certifi-servicios.txt
# - name: Obtener Hostname
#   shell: |
#     echo '============================================== HOSTNAME =======================================' >> /Certifi-servicios/Certifi-servicios.txt
#     hostname  >> /Certifi-servicios/Certifi-servicios.txt
# - name: Obtener IP Server
#   shell: |
#     echo '============================================== IP SERVER ======================================' >> /Certifi-servicios/Certifi-servicios.txt
#     nmcli | grep "inet4" >> /Certifi-servicios/Certifi-servicios.txt
# - name: Obtener Servicio IpTables
#   shell: |
#     echo '============================================== SERVICIO IPTABLES ==============================' >> /Certifi-servicios/Certifi-servicios.txt
#     systemctl status iptables >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Obtener FileSystem Montados
#   shell: |
#     echo '============================================== FILESYSTEM MONTADOS ============================' >> /Certifi-servicios/Certifi-servicios.txt
#     df -h >> /Certifi-servicios/Certifi-servicios.txt
# - name: Obtener Servicios Activos
#   shell: |
#     echo '============================================== SERVICIOS ACTIVOS ==============================' >> /Certifi-servicios/Certifi-servicios.txt
#     systemctl list-units --type service --all | grep -w "active" >> /Certifi-servicios/Certifi-servicios.txt
# - name: Obtener Servicio NFS
#   shell: |
#     echo '============================================= SERVICIOS NFS ==================================' >> /Certifi-servicios/Certifi-servicios.txt
#     systemctl status nfs >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Obtener Servicios Java
#   shell: |
#     echo '============================================== SERVICIOS JAVA ================================' >> /Certifi-servicios/Certifi-servicios.txt
#     ps -fea | grep "java" >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: /Certifi-servicios/Certifi-servicios.txt
#     state: absent
#     regexp: './bin/sh*'
# - name: Obtener Servicios Jboss
#   shell: |
#     echo '============================================== SERVICIOS JBOSS/GLASSFISH/APACHE TOMCAT========' >> /Certifi-servicios/Certifi-servicios.txt
#     ps -fea | grep "jboss" >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: /Certifi-servicios/Certifi-servicios.txt
#     state: absent
#     regexp: './bin/sh*'
# - name: Obtener Servicios Apache
#   shell: |
#     echo '============================================== SERVICIOS APACHE ==============================' >> /Certifi-servicios/Certifi-servicios.txt
#     ps -fea | grep "http" >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: /Certifi-servicios/Certifi-servicios.txt
#     state: absent
#     regexp: './bin/sh*'
# - name: Obtener Servicios Control-M
#   shell: |
#     echo '============================================== SERVICIOS CONTROL-M ===========================' >> /Certifi-servicios/Certifi-servicios.txt
#     ps -fea | grep "cmagt" >> /Certifi-servicios/Certifi-servicios.txt
#   ignore_errors: yes
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: /Certifi-servicios/Certifi-servicios.txt
#     state: absent
#     regexp: './bin/sh*'
# - name: Obtener Punto de Montaje
#   shell: |
#     echo '============================================== PUNTO DE MONTAJE ==============================' >> /Certifi-servicios/Certifi-servicios.txt
#     mount >> /Certifi-servicios/Certifi-servicios.txt
# - name: Imprimir Linea Final
#   shell: |
#     echo '############################################### FIN DE LOS SERVICIOS ###########################################################################' >> /Certifi-servicios/Certifi-servicios.txt
