- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Deshabilitar SeLinux
  selinux:
    conf: "{{ path_selinux }}"
    state: "{{ state_selinux }}"
