- name: Crear Directorio Certifi-servicios
  file:
    path: "{{ directorio_salidacertifiserv }}"
    state: directory
    force: yes

- name: Copiar Ficheros a Certifi-servicios
  copy:
    src: "{{ item }}"
    dest: "{{ directorio_salidacertifiserv }}"
    force: yes
  loop: "{{ ficheros_etc }}"
  ignore_errors: yes

- name: Leer Ficheros IpTables
  command: "cat {{ path_iptables }}"
  register: iptables_out

- name: Copiar Ficheros Iptables a Certifi-servicios
  copy:
    content: "{{ iptables_out.stdout }}"
    dest: "{{ directorio_salidacertifiserv }}/iptables"

- name: Leer Ficheros Fstab
  command: "cat {{ path_fstab }}"
  register: fstab_out

- name: Copiar Ficheros Fstab a Certifi-servicios
  copy:
    content: "{{ fstab_out.stdout }}"
    dest: "{{ directorio_salidacertifiserv }}/fstab"

- name: Leer Ficheros sshd_config
  command: cat /etc/ssh/sshd_config
  register: sshdconfig_out

- name: Copiar Ficheros sshd_config a Certifi-servicios
  copy:
    content: "{{ sshdconfig_out.stdout }}"
    dest: "{{ directorio_salidacertifiserv }}/sshd_config"

- name: Crear Fichero Certifi-servicios
  copy:
    content: ""
    dest: "{{ path_salidacertifiserv }}"
    force: yes

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS ACTIVOS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  HOSTNAME SERVER  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Hostname Server
  command: hostname
  register: hostname_out

- name: Imprimir Hostname Server
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ hostname_out.stdout }}"

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  IP SERVER  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener IP Server
  shell: nmcli | grep "inet4"
  register: ip_out

- name: Imprimir IP Server
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ ip_out.stdout }}"

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIO IPTABLES  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Servicio IpTables
  command: systemctl status iptables
  register: iptables_out
  ignore_errors: yes

- name: Ignorando Warning / Error
  debug:
    msg: "Comando Nativo sin Retorno -- Ignorando -- Agregando Informacion"

- name: Imprimir IP Tables
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ iptables_out.stdout }}"
  ignore_errors: yes

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  FILESYSTEM MONTADOS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener FyleSystem
  command: df -h
  register: df_out

- name: Imprimir FyleSystem
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ df_out.stdout }}"

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS ACTIVOS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Servicios Activos
  shell: systemctl list-units --type service --all | grep -w "active"
  register: services_out

- name: Imprimir Servicios Activos
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ services_out.stdout }}"

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS NFS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Servicios NFS
  command: systemctl status nfs
  register: nfs_out
  ignore_errors: yes

- name: Ignorando Warning / Error
  debug:
    msg: "Comando Nativo sin Retorno -- Ignorando -- Agregando Informacion"

- name: Imprimir Servicios NFS
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ nfs_out.stdout }}"
  ignore_errors: yes

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS JAVA  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Servicios Java
  shell: ps -fea | grep "java"
  register: java_out

- name: Imprimir Servicios Java
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ java_out.stdout }}"

- name: Eliminar Resultado Extra
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    state: absent
    regexp: './bin/sh.'

# - name: Imprimir Linea Inicial
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS JBOSS/GLASSFISH/APACHE TOMCAT  <<<<<<<<<<<<<<<<<<<<<<<<<<"
#
# - name: Obtener Servicios Jboss
#   shell: ps -fea | grep "jboss"
#   register: jboss_out
#
# - name: Imprimir Servicios Jboss
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     line: "{{ jboss_out.stdout }}"
#
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     state: absent
#     regexp: './bin/sh.'
#
# - name: Imprimir Linea Inicial
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS APACHE  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
#
# - name: Obtener Servicios Apache
#   shell: ps -fea | grep "http"
#   register: apache_out
#
# - name: Imprimir Servicios Apache
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     line: "{{ apache_out.stdout }}"
#
# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     state: absent
#     regexp: './bin/sh.'

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  SERVICIOS CONTROL-M  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Servicios CONTROL-M
  shell: ps -fea | grep cmagt
  register: crtlm_out

- name: Imprimir Servicios CONTROL-M
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ crtlm_out.stdout }}"

- name: Eliminar Resultado Extra
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    state: absent
    regexp: './bin/sh.'

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  INSTANCIA BD (Solo Base de datos)  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Instancia BD
  shell: ps -fea | grep smon
  register: smon_out

- name: Imprimir Instancia BD
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ smon_out.stdout }}"

# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     state: absent
#     regexp: "./bin/sh."

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Pmon
  shell: ps -fea | grep pmon
  register: pmon_out

- name: Imprimir Pmon
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ pmon_out.stdout }}"

# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     state: absent
#     regexp: "./bin/sh."

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  CRS (Solo Base de Datos)  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener CRS
  shell: ps -fea |grep d.bin
  register: dbin_out

- name: Imprimir CRS
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ dbin_out.stdout }}"

# - name: Eliminar Resultado Extra
#   lineinfile:
#     path: "{{ path_salidacertifiserv }}"
#     state: absent
#     regexp: "./bin/sh."

- name: Imprimir Linea Inicial
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  PUNTO DE MONTAJE  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

- name: Obtener Punto de Montaje
  command: mount
  register: mount_out

- name: Imprimir Punto Montaje
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: "{{ mount_out.stdout }}"

- name: Imprimir Linea Final
  lineinfile:
    path: "{{ path_salidacertifiserv }}"
    line: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FIN SERVICIOS ACTIVOS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
