- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Deshabilitar Firewalld
  service:
    name: firewalld
    enabled: false
    state: stopped

- name: Aplicar Mask a Firewalld
  systemd:
    name: firewalld
    masked: yes
    state: stopped

- name: Instalar Iptables
  yum:
    name: iptables-services
    state: latest

- name: Copiar Archivo Configuracion IpTables
  copy:
    src: iptables
    dest: "{{ path_iptables }}"
    owner: "{{ usuario_iptables }}"
    group: "{{ grupo_iptables }}"
    mode: "{{ permisos_iptables }}"
    force: yes

- name: Iniciar-Iptables
  service:
    name: iptables
    enabled: true
    state: restarted
