- name: Iniciar Configuracion de llaves SSH
  debug:
    msg: "Iniciar Configuracion de llaves SSH"

- name: Generar llaves SSH para Usuarios
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    state: present
  loop: "{{ usuarios_ssh }}"

- name: Copiar LLaves SSH para Usuario Oracle
  shell: "/usr/bin/ssh-copy-id -f oracle@{{ item }}"
  loop: "{{ lista_ips_rac }}"

- name: Copiar LLaves SSH para Usuario Grid
  shell: "/usr/bin/ssh-copy-id -f grid@{{ item }}"
  loop: "{{ lista_ips_rac }}"

- name: Establecer Conexion Inicial Usuario Oracle
  become_user: oracle
  shell: "/usr/bin/ssh -o StrictHostKeyChecking=no oracle@{{ item }} date"
  loop: "{{ lista_ips_rac }}"

- name: Establecer Conexion Inicial Usuario Grid
  become_user: oracle
  shell: "/usr/bin/ssh -o StrictHostKeyChecking=no grid@{{ item }} date"
  loop: "{{ lista_ips_rac }}"
