- name: Iniciar Configuracion de llaves SSH
  debug:
    msg: "Iniciar Configuracion de llaves SSH"

- name: Generar llaves SSH para Usuarios
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    state: present
  loop: "{{ usuarios_ssh }}"

- name: Copiar Expect SshKeys Admin
  copy:
    src: "{{ nombre_expect_sshkeys }}"
    dest: "{{ path_destino_exp }}"
    owner: "{{ usuario_oracle }}"
    group: "{{ grupo_oracle }}"
    mode: "{{ modo_oracle }}"
    force: yes
- pause:
    seconds: 2

- name: Copiar Llaves SSh Para Usuario Oracle
  command: "expect {{ path_destino_exp }}/{{ nombre_expect_sshkeys }} {{ item }} {{ oracle_pwd }} "
  loop: "{{ lista_ips_rac }}"

# - name: Copiar LLaves SSH para Usuario Oracle
#   become_user: oracle
#   shell: "/usr/bin/ssh-copy-id -f -i /home/oracle/.ssh/id_rsa.pub -o StrictHostKeyChecking=no {{ item }}"
#   loop: "{{ lista_ips_rac }}"
#
# - name: Copiar LLaves SSH para Usuario Grid
#   become_user: grid
#   shell: "/usr/bin/ssh-copy-id -f -i /home/grid/.ssh/id_rsa.pub -o StrictHostKeyChecking=no {{ item }}"
#   loop: "{{ lista_ips_rac }}"

# - name: Establecer Conexion Inicial Usuario Oracle
#   become_user: oracle
#   shell: "/usr/bin/ssh -o StrictHostKeyChecking=no oracle@{{ item }} date"
#   loop: "{{ lista_ips_rac }}"
#
# - name: Establecer Conexion Inicial Usuario Grid
#   become_user: grid
#   shell: "/usr/bin/ssh -o StrictHostKeyChecking=no grid@{{ item }} date"
#   loop: "{{ lista_ips_rac }}"
