- name: Iniciar Configuracion de llaves SSH
  debug:
    msg: "Iniciar Configuracion de llaves SSH"

- name: Generar llaves SSH para Usuarios
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    state: present
  loop:
    - "{{ usuario_oracle }}"
    - "{{ usuario_grid }}"

- name: Descargar llaves publicas Nodo 1 Usuario Oracle
  fetch:
    src: "{{ path_keys_publicas_oracle }}"
    dest: "{{ usuario_oracle }}_id_rsa.{{ ip_nombre_node1 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Descargar llaves publicas Nodo 1 Usuario Grid
  fetch:
    src: "{{ path_keys_publicas_grid }}"
    dest: "{{ usuario_grid }}_id_rsa.{{ ip_nombre_node1 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Descargar llaves publicas Nodo 1 Usuario Root
  fetch:
    src: "{{ path_keys_publicas_root }}"
    dest: "{{ usuario_root }}_id_rsa.{{ ip_nombre_node1 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Descargar llaves publicas Nodo 2 Usuario Oracle
  fetch:
    src: "{{ path_keys_publicas_oracle }}"
    dest: "{{ usuario_oracle }}_id_rsa.{{ ip_nombre_node2 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node2 }}"

- name: Descargar llaves publicas Nodo 2 Usuario Grid
  fetch:
    src: "{{ path_keys_publicas_grid }}"
    dest: "{{ usuario_grid }}_id_rsa.{{ ip_nombre_node2 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node2 }}"

- name: Descargar llaves publicas Nodo 2 Usuario Root
  fetch:
    src: "{{ path_keys_publicas_root }}"
    dest: "{{ usuario_root }}_id_rsa.{{ ip_nombre_node2 }}"
    flat: yes
  loop: "{{ groups['all'] }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"

- name: Copiar llaves Publicas a todos los nodos Usuario Oracle
  become: yes
  become_user: "{{ usuario_oracle }}"
  authorized_key:
    user: "{{ usuario_oracle }}"
    key: "{{ lookup('file', '{{ usuario_oracle }}_id_rsa.{{ item }}') }}"
    state: present
  loop: "{{ groups['all'] }}"

- name: Copiar llaves Publicas a todos los nodos Usuario Grid
  become: yes
  become_user: "{{ usuario_grid }}"
  authorized_key:
    user: "{{ usuario_grid }}"
    key: "{{ lookup('file', '{{ usuario_grid }}_id_rsa.{{ item }}') }}"
    state: present
  loop: "{{ groups['all'] }}"

- name: Copiar llaves Publicas a todos los nodos Usuario Root
  become: yes
  become_user: "{{ usuario_root }}"
  authorized_key:
    user: "{{ usuario_root }}"
    key: "{{ lookup('file', '{{ usuario_root }}_id_rsa.{{ item }}') }}"
    state: present
  loop: "{{ groups['all'] }}"

- name: Verificar existencia del fichero known hosts Usuario Oracle
  become: yes
  become_user: "{{ usuario_oracle }}"
  file:
    path: ~/.ssh/known_hosts
    state: touch

- name: Verificar existencia del fichero known hosts Usuario Grid
  become: yes
  become_user: "{{ usuario_grid }}"
  file:
    path: ~/.ssh/known_hosts
    state: touch

- name: Verificar existencia del fichero known hosts Usuario Root
  become: yes
  become_user: "{{ usuario_root }}"
  file:
    path: ~/.ssh/known_hosts
    state: touch

- name: Agregar hosts al fichero known_hosts Usuario Oracle
  become: yes
  become_user: "{{ usuario_oracle }}"
  shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
  loop: "{{ groups['all'] }}"

- name: Agregar hosts al fichero known_hosts Usuario Grid
  become: yes
  become_user: "{{ usuario_grid }}"
  shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
  loop: "{{ groups['all'] }}"

- name: Agregar hosts al fichero known_hosts Usuario Grid
  become: yes
  become_user: "{{ usuario_root }}"
  shell: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
  loop: "{{ groups['all'] }}"
