- name: Versión Jboss 6
  debug:
    msg: "Iniciar Ejecución de JBoss EAP Version: 6"

- name: Crear Directorios Punto de Montaje
  file:
    path: "{{ item }}"
    state: directory
    force: yes
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"
  loop:
    - "{{ punto_montaje_nfs }}"

- name: Instalar NFS-Utils
  yum:
    name: nfs-utils
    state: present

- name: Agregar Recurso NFS Fstab
  lineinfile:
    path: "{{ path_fstab }}"
    line: "{{ recurso_nfs }}"

- name: Montar Recurso NFS
  command: "mount -a"

- name: Elimar Version Actual de Java
  yum:
    name: java
    state: absent

# - name: Copiar Oracle JDK 8
#   become: true
#   become_method: su
#   become_user: root
#   copy:
#     src:  "{{ punto_montaje_nfs }}/{{ nombre_oracle_jdk8 }}"
#     dest: /var/tmp/
#     owner: "{{ usaurio_jboss }}"
#     group: "{{ grupo_jboss }}"
#     mode: "{{ jdk_permisos }}"
#     force: yes
# - pause:
#     seconds: 2

- name: Instalar Oracle JDK 8
  yum:
    # name: "/var/tmp/{{ nombre_oracle_jdk8 }}"
    name: "{{ punto_montaje_nfs }}/{{ nombre_oracle_jdk8 }}"
    state: present
    disable_gpg_check: yes

- name: Descomprimir Jboss EAP 6 ZIP
  unarchive:
    src: "{{ punto_montaje_nfs }}/{{ nombre_jboss6_zip }}"
    dest: "{{ path_instalacion }}"
    copy: false
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"

- name: Agregar Valor a mgmt-users.properties
  lineinfile:
    path: "{{ path_mgmt_userp6 }}"
    line: "{{ item }}"
  loop: "{{ mgmt_user_properties_value }}"

- name: Agregar Valor a mgmt-groups.properties
  lineinfile:
    path: "{{ path_mgmt_groupp6 }}"
    line: "{{ item }}"
  loop: "{{ mgmt_groups_properties_value }}"

# - name: Preparar Template de Configuracion StandAlone.xml
#   template:
#     src: "{{ nombre_template6 }}"
#     dest: "{{ path_fichero_standalone6 }}"

- name: Setear Variable de Entorno Java Home
  lineinfile:
    dest: "{{ path_bashprofile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "export PATH"
  loop:
    -
      regexp: ^JAVA_HOME=
      line: "JAVA_HOME={{ java_home }}"
    -
      regexp: PATH=\$JAVA_HOME/bin
      line: PATH=$JAVA_HOME/bin:$PATH
    -
      regexp: ^export JAVA_HOME
      line: export JAVA_HOME

- name: Setear Variable de Entorno Jboss Home
  lineinfile:
    dest: "{{ path_bashprofile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "export PATH"
  loop:
    -
      regexp: ^JBOSS_HOME=
      line: "JBOSS_HOME={{ jboss6_home }}"
    -
      regexp: PATH=\$JBOSS_HOME
      line: PATH=$JBOSS_HOME:$PATH
    -
      regexp: ^export JBOSS_HOME
      line: export JBOSS_HOME

- name: Recargar Variables de Entorno
  shell: "source {{ path_bashprofile }}"
