- name: Version Jboss 7
  debug:
    msg: "Iniciar Ejecución de JBoss EAP Version: 7"

- name: Ejecutar Instalacion de Oracle JDK
  include: installjdk8.yml

- name: Copiar Jboss EAP 7 ZIP
  copy:
    src: "{{ path_recursos_maestro }}/{{ nombre_jboss7_zip }}"
    dest: "{{ path_recursos_nodo }}"
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"

- name: Descomprimir Jboss EAP 7 ZIP
  unarchive:
    src: "{{ path_recursos_nodo }}/{{ nombre_jboss7_zip }}"
    dest: "{{ path_jbosseap }}"
    copy: false
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"

- name: Agregar Valor a mgmt-users.properties
  lineinfile:
    path: "{{ path_mgmt_userp7 }}"
    line: "{{ item }}"
  loop: "{{ mgmt_user_properties_value }}"

- name: Agregar Valor a mgmt-groups.properties
  lineinfile:
    path: "{{ path_mgmt_groupp7 }}"
    line: "{{ item }}"
  loop: "{{ mgmt_groups_properties_value }}"

- name: Preparar Template de Configuracion StandAlone.xml
  template:
    src: "{{ nombre_template7 }}"
    dest: "{{ path_fichero_standalone7 }}"

- name: Setear Variable de Entorno Java Home
  lineinfile:
    dest: "{{ path_bashprofile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "export PATH"
  loop:
    -
      regexp: ^JAVA_HOME=
      line: "JAVA_HOME={{ java_home }}"
    -
      regexp: PATH=\$JAVA_HOME/bin
      line: PATH=$JAVA_HOME/bin:$PATH
    -
      regexp: ^export JAVA_HOME
      line: export JAVA_HOME

- name: Setear Variable de Entorno Jboss Home
  lineinfile:
    dest: "{{ path_bashprofile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "export PATH"
  loop:
    -
      regexp: ^JBOSS_HOME=
      line: "JBOSS_HOME={{ jboss7_home }}"
    -
      regexp: PATH=\$JBOSS_HOME
      line: PATH=$JBOSS_HOME:$PATH
    -
      regexp: ^export JBOSS_HOME
      line: export JBOSS_HOME

- name: Recargar Variables de Entorno
  shell: "source {{ path_bashprofile }}"
