- name: Versión Jboss 6
  debug:
    msg: "Iniciar Ejecución de JBoss EAP Version: 6"

- name: Crear Directorios
  file:
    path: "{{ item }}"
    state: directory
    force: yes
  loop:
    # - "{{ punto_montaje_nfs }}"
    - "{{ path_java }}"

- name: Copiar Oracle JDK 8 ZIP
  copy:
    src: "{{ path_recursos_maestro }}/{{ nombre_oraclejdk8_zip }}"
    dest: "{{ path_recursos_nodo }}"
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"
  when: "{{ version_jdk }}" == "8"

- name: Copiar Oracle JDK 7 ZIP
  copy:
    src: "{{ path_recursos_maestro }}/{{ nombre_oraclejdk7_zip }}"
    dest: "{{ path_recursos_nodo }}"
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"
  when: "{{ version_jdk }}" == "7"

- name: Elimar Version Actual de Java
  yum:
    name: java
    state: absent

- name: Instalar Oracle JDK 8
  unarchive:
    src: "{{ path_recursos_nodo }}/{{ nombre_oraclejdk8_zip }}"
    dest: "{{ path_java }}"
    copy: false
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"
  when: "{{ version_jdk }}" == "8"

- name: Instalar Oracle JDK 7
  unarchive:
    src: "{{ path_recursos_nodo }}/{{ nombre_oraclejdk7_zip }}"
    dest: "{{ path_java }}"
    copy: false
    owner: "{{ usaurio_jboss }}"
    group: "{{ grupo_jboss }}"
    mode: "{{ jboss_home_permisos }}"
  when: "{{ version_jdk }}" == "7"

# - name: Copiar Jboss EAP 6 ZIP
#   copy:
#     src: "{{ path_recursos_maestro }}/{{ nombre_jboss6_zip }}"
#     dest: "{{ path_recursos_nodo }}"
#     owner: "{{ usaurio_jboss }}"
#     group: "{{ grupo_jboss }}"
#     mode: "{{ jboss_home_permisos }}"
#
# - name: Descomprimir Jboss EAP 6 ZIP
#   unarchive:
#     src: "{{ path_recursos_nodo }}/{{ nombre_jboss6_zip }}"
#     dest: "{{ path_jbosseap }}"
#     copy: false
#     owner: "{{ usaurio_jboss }}"
#     group: "{{ grupo_jboss }}"
#     mode: "{{ jboss_home_permisos }}"
#
# - name: Agregar Valor a mgmt-users.properties
#   lineinfile:
#     path: "{{ path_mgmt_userp6 }}"
#     line: "{{ item }}"
#   loop: "{{ mgmt_user_properties_value }}"
#
# - name: Agregar Valor a mgmt-groups.properties
#   lineinfile:
#     path: "{{ path_mgmt_groupp6 }}"
#     line: "{{ item }}"
#   loop: "{{ mgmt_groups_properties_value }}"
#
# - name: Preparar Template de Configuracion StandAlone.xml
#   template:
#     src: "{{ nombre_template6 }}"
#     dest: "{{ path_fichero_standalone6 }}"
#
# - name: Setear Variable de Entorno Java Home
#   lineinfile:
#     dest: "{{ path_bashprofile }}"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     insertbefore: "export PATH"
#   loop:
#     -
#       regexp: ^JAVA_HOME=
#       line: "JAVA_HOME={{ java_home }}"
#     -
#       regexp: PATH=\$JAVA_HOME/bin
#       line: PATH=$JAVA_HOME/bin:$PATH
#     -
#       regexp: ^export JAVA_HOME
#       line: export JAVA_HOME
#
# - name: Setear Variable de Entorno Jboss Home
#   lineinfile:
#     dest: "{{ path_bashprofile }}"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     insertbefore: "export PATH"
#   loop:
#     -
#       regexp: ^JBOSS_HOME=
#       line: "JBOSS_HOME={{ jboss6_home }}"
#     -
#       regexp: PATH=\$JBOSS_HOME
#       line: PATH=$JBOSS_HOME:$PATH
#     -
#       regexp: ^export JBOSS_HOME
#       line: export JBOSS_HOME
#
# - name: Recargar Variables de Entorno
#   shell: "source {{ path_bashprofile }}"
