- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Actualizar Sistema
  yum:
    name: "*"
    state: latest
- pause:
    seconds: 2

- name: Instalar Paquetes
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ paquetes_prerrequisitos }}"
- pause:
    seconds: 2

- name: Agregar Limits Usuario Jboss
  lineinfile:
    dest: "{{ path_limits }}"
    line: "{{ usuario_jboss }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items:
    - { limit: 'soft', type: nproc, value: '{{ jboss_limits_soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ jboss_limits_hard_nproc }}' }
    - { limit: 'soft', type: nofile, value: '{{ jboss_limits_soft_nofile }}' }
    - { limit: 'hard', type: nofile, value: '{{ jboss_limits_hard_nofile }}' }

- name: Agregar Limits Usuario Root
  lineinfile:
    dest: "{{ path_limits }}"
    line: "{{ usuario_root }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items:
    - { limit: 'soft', type: nproc, value: '{{ root_limits_soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ root_limits_hard_nproc }}' }
    - { limit: 'soft', type: nofile, value: '{{ root_limits_soft_nofile }}' }
    - { limit: 'hard', type: nofile, value: '{{ root_limits_hard_nofile }}' }

- name: Detener IpTables
  service:
    name: iptables
    state: stopped
  ignore_errors: yes
