- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Particionar Discos
  become: yes
  become_user: "{{ usuario_root }}"
  parted:
    device: "{{ item.device }}"
    number: "{{ item.number }}"
    part_end:   100%
    part_type:  primary
    state: present
    unit: MB
  loop: "{{ discos_particionar }}"
  when: inventory_hostname == "{{ ip_nombre_node1 }}"
