- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Cambiar metodo de encryptacion a SHA512
  replace:
    path: "{{ path_loginencrypt }}"
    regexp: ".*ENCRYPT_METHOD.*"
    replace: "ENCRYPT_METHOD {{ method_encrypt_login }}"
