- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Desactivar servicios NO necesarios
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: yes
  loop: "{{ lista_servicios_off }}"
