- name: "Cadena de Conexion"
  rhevm:
    name: "{{ nombre_maquinavirtual }}"
    user: "{{ usuario_servidor }}"
    password: "{{ password_servidor }}"
    server: "{{ nombre_ip_servidor }}"
    cluster: "{{ nombre_cluster }}"
    datacenter: "{{ nombre_datacenter }}"

- name: Desactivar acceso a ROOT por ssh
  replace:
    path: "{{ path_ssh }}"
    regexp: ".*PermitRootLogin.*"
    replace: "PermitRootLogin {{permit_root_login}}"
  notify: Reiniciar-Sshd
