#Nombre Fichero sshkeysadmin.exp
nombre_expect_sshkeys: sshkeysadmin.exp
#Path destino Fichero sshkeysadmin.exp
path_destino_exp: /tmp
#Pass SSH Oracle:
oracle_pwd: 222
#Pass SSH Grid:
grid_pwd: 222
#Nombre / Ip del nodo 1
ip_nombre_node1: 192.168.72.XXX
#Nombre / Ip del nodo 2
ip_nombre_node2: 192.168.72.XXX
#Usuario Grid Para ejecucion de Expect
usuario_grid: grid
#Grupo Propietario de directorios BD Oracle
usuario_oracle: oracle
#Grupo Propietario de directorios BD Oracle
grupo_oracle: oinstall
#Modo para Fichero sshkeysadmin.exp
modo_oracle: 0777
#Usuario al que se escalan los permisos
usuario_become: root
#Path de llaves publicas usuario oracle
path_keys_publicas: /home/{{ usuario_oracle }}/.ssh/id_rsa.pub

#Lista de Usuarios para Generar llaves SSH
usuarios_ssh:
  - oracle
  - grid

#Lista de fully qualified domain name del RAC
lista_ips_rac:
  #Ips Publicas
  - 192.168.72.170
  - 192.168.72.180
  #Ips Privadas
  - 192.168.1.170
  - 192.168.1.180
  #IPs Virtuales
  - 192.168.72.171
  - 192.168.72.181
