#Datos de la cadena Conexion
nombre_maquinavirtual:
usuario_servidor:
password_servidor:
nombre_ip_servidor:
nombre_cluster:
nombre_datacenter:

#Path fichero login.defs
path_loginencrypt: /etc/login.defs
#Metodo de ecnriptacion login
method_encrypt_login: SHA512
