- name: "Ejecucion de SecurityCheck APP"
  hosts: all
  become: true
  roles:
    - serviciosOff
    - loginEncrypt
    - configNtp
    - usersUnix
    - usersMonitor
    - usersJboss
    - configSelinux
    - ipTables
    - prerrequisitos
    #- sshRoot
